name: CI/CD Despliegue Automático en Render

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy-to-render:
    name: Actualizar Contenedor en Render
    runs-on: ubuntu-latest
    steps:
      - name: Confirmar Push a la Rama Principal
        run: echo "¡Nuevo commit detectado en la rama principal! Iniciando pipeline..."

      - name: Ejecutar Deploy Hook de Render
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
          echo "¡Orden de actualización enviada exitosamente a Render!"
